/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lighthouse;

public class Lighthouse {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Lighthouse().getGreeting());
    }
}
